Add first implementation of collision between snake and apple
X-R-G-B/Arcade pull request #63
Opened 2023-03-30 20:22 UTC by KitetsuK

2023-03-31 11:54 UTC, Saverio976 commented
(brice va faire des modif sur cette PR)

2023-03-31 11:58 UTC, Saverio976 requested changes

2023-03-31 11:58 UTC, Saverio976 commented on src/GameLibs/Snake/System/AppleSystem.cpp
> +        eventManager.clearEvents();
pas besoin, comme discuté, les events sont clear dans le core

2023-03-31 11:58 UTC, Saverio976 commented on src/GameLibs/Snake/System/Collision.cpp
> +    std::shared_ptr<Arcade::ECS::IEntity> snakeEntity = currentEntityManager.getEntitiesById("Snake");
magick value (il y a un fichier MagickValue.hpp

2023-03-31 11:58 UTC, Saverio976 commented on src/GameLibs/Snake/System/Collision.cpp
> +    std::shared_ptr<Arcade::ECS::IEntity> appleEntity = currentEntityManager.getEntitiesById("Apple");
MagickValue.hpp

2023-03-31 11:58 UTC, Saverio976 commented on src/GameLibs/Snake/System/Collision.cpp
> +    Arcade::ECS::IComponent &snakeHeadIComp = snakeEntity->getComponents("Snake Head");
MagickValue.hpp

2023-03-31 11:58 UTC, Saverio976 commented on src/GameLibs/Snake/System/Collision.cpp
> +    Arcade::ECS::IComponent &appleIComp = appleEntity->getComponents("apple");
MagickValue.hpp

2023-03-31 11:58 UTC, Saverio976 commented on src/GameLibs/Snake/System/Collision.cpp
> +#include "CompType.hpp"
utilises plutôt SnakeCompType.hpp

2023-03-31 13:00 UTC, guillaumeAbel requested changes

2023-03-31 16:33 UTC, Saverio976 commented
tu t'es toujour pas assigné

2023-03-31 16:34 UTC, Saverio976 requested changes

2023-03-31 16:34 UTC, Saverio976 commented on src/GameLibs/Snake/System/EatSystem.cpp
> +    std::shared_ptr<Arcade::ECS::IEntity> snakeEntity = currentEntityManager.getEntitiesById(SNAKE_ENTITY);
auto

2023-04-01 23:59 UTC, Saverio976 requested changes

2023-04-01 23:59 UTC, Saverio976 commented on src/GameLibs/Snake/Component/SnakeCompType.hpp
> +            MOVEABLE = 101,
201

2023-04-01 23:59 UTC, Saverio976 commented on src/GameLibs/Snake/Component/SnakeCompType.hpp
> +            BODY_INCR = 102
203

2023-04-02 00:00 UTC, Saverio976 commented
et merge conflict

2023-04-02 15:39 UTC, guillaumeAbel requested changes

2023-04-02 15:39 UTC, guillaumeAbel commented on src/GameLibs/Snake/System/EatSystem.cpp
> +    auto &snakeIncrComp = snakeEntity->getComponents("snakegrow");
```suggestion
    auto &snakeIncrComp = snakeEntity->getComponents(SNAKE_GROW_COMPONENT);
```

2023-04-02 15:39 UTC, guillaumeAbel commented on src/GameLibs/Snake/System/EatSystem.cpp
> +    auto &snakeIncrComp = snakeEntity->getComponents("snakegrow");
sah la fonctionnalité de fou

2023-04-02 15:39 UTC, guillaumeAbel commented on src/GameLibs/Snake/System/EatSystem.cpp
> +            snakeIncrComp.grow += 1;
Apple should change pos

2023-04-02 18:28 UTC, Saverio976 commented on src/GameLibs/Snake/System/EatSystem.cpp
> +    auto &snakeIncrComp = snakeEntity->getComponents("snakegrow");
réel

2023-04-02 18:28 UTC, Saverio976 commented on src/GameLibs/Snake/System/EatSystem.cpp
> +    auto &snakeIncrComp = snakeEntity->getComponents("snakegrow");
en plus on peut direct commit le truc

2023-04-02 18:54 UTC, KitetsuK commented on src/GameLibs/Snake/System/EatSystem.cpp
> +    auto &snakeIncrComp = snakeEntity->getComponents("snakegrow");
ca met bien

2023-04-02 19:09 UTC, guillaumeAbel approved these changes

2023-04-02 19:10 UTC, merged