Arcade 96 implementer snake entity
X-R-G-B/Arcade pull request #66
Opened 2023-04-01 20:48 UTC by guillaumeAbel

2023-04-01 23:53 UTC, Saverio976 requested changes

2023-04-01 23:53 UTC, Saverio976 commented on src/GameLibs/Snake/Snake.cpp
> +    head.addComponent(std::make_shared<Component::Moveable>("dir", Direction::RIGHT));
rregarde magickvalue il y a la valeur je crois

2023-04-01 23:53 UTC, Saverio976 commented on src/GameLibs/Snake/Snake.cpp
> +    snake.addComponent(std::make_shared<Component::SnakeGrow>("snakegrow"));
magick value ? (magickvalue.hpp)

2023-04-02 00:15 UTC, guillaumeAbel commented on src/GameLibs/Snake/Snake.cpp
> +    head.addComponent(std::make_shared<Component::Moveable>("dir", Direction::RIGHT));
nope, je l'ajoute

2023-04-02 00:58 UTC, Saverio976 commented
merge conflict

2023-04-02 00:58 UTC, Saverio976 approved these changes

2023-04-02 01:26 UTC, Saverio976 approved these changes

2023-04-02 01:26 UTC, merged