Arcade 139 restart system
X-R-G-B/Arcade pull request #67
Opened 2023-04-01 22:42 UTC by guillaumeAbel

2023-04-01 22:42 UTC, guillaumeAbel commented
Contain ARCADE-96 modifs, acutally in pr

2023-04-01 23:55 UTC, Saverio976 requested changes

2023-04-01 23:55 UTC, Saverio976 commented on src/GameLibs/Snake/System/Restart.cpp
> +    eventManager.isEventTriggered("RESTART");
il manque un if non ?

2023-04-01 23:55 UTC, Saverio976 commented on src/GameLibs/Snake/System/Restart.hpp
> +                std::unique_ptr<Arcade::Game::IScene> &_scene;
tu prends la scene de game ?

2023-04-02 00:04 UTC, guillaumeAbel commented on src/GameLibs/Snake/System/Restart.cpp
> +    eventManager.isEventTriggered("RESTART");
waah ah oe

2023-04-02 00:05 UTC, guillaumeAbel commented on src/GameLibs/Snake/System/Restart.hpp
> +                std::unique_ptr<Arcade::Game::IScene> &_scene;
oui j'ai besoin de la close et init dans le run

2023-04-02 01:31 UTC, Saverio976 approved these changes

2023-04-02 01:32 UTC, merged