Arcade 143 implementer sprite
X-R-G-B/Arcade pull request #84
Opened 2023-04-04 13:59 UTC by KitetsuK

2023-04-04 14:19 UTC, romainpanno requested changes

2023-04-04 14:19 UTC, romainpanno commented on CMakeLists.txt
> +    COMPILE_FLAGS "-fno-gnu-unique -lSDL2 -lSDL2_image"
use find_library() instead

2023-04-04 14:19 UTC, romainpanno commented on src/Arcade/ECS/CompType.hpp
> +/*#include "GraphStruct.hpp"
??

2023-04-04 14:19 UTC, romainpanno commented on src/GraphicLibs/SDL/CMakeLists.txt
> +        )
remove tab

2023-04-04 14:19 UTC, romainpanno commented on src/GraphicLibs/SDL/SDL.hpp
> +}
EOF

2023-04-04 14:19 UTC, romainpanno commented on src/GraphicLibs/SDL/Sprite.hpp
> +}
OEF

2023-04-04 14:43 UTC, romainpanno requested changes

2023-04-04 14:43 UTC, romainpanno commented on src/GraphicLibs/SDL/CMakeLists.txt
> +target_link_libraries(arcade_sdl2 PRIVATE ${LSDLGRAPHICS})
EOF

2023-04-04 15:45 UTC, Saverio976 requested changes

2023-04-04 15:45 UTC, Saverio976 commented on src/GraphicLibs/SDL/Sprite.cpp
> +    sprite = SDL_LoadBMP(path.data());
que des bmp ?

2023-04-04 16:02 UTC, KitetsuK commented on src/GraphicLibs/SDL/Sprite.cpp
> +    sprite = SDL_LoadBMP(path.data());
Bah j'arrive pas à trouver d'autres fonctions qui load l'image, je cherche et je te dis

2023-04-04 16:03 UTC, KitetsuK commented on src/GraphicLibs/SDL/Sprite.cpp
> +    sprite = SDL_LoadBMP(path.data());
/**
 * Load a surface from a file.
 *
 * Convenience macro.
 */
#define SDL_LoadBMP(file)   SDL_LoadBMP_RW(SDL_RWFromFile(file, "rb"), 1)

Je penses que ca marche pour n'importe quelle type de file

2023-04-05 09:04 UTC, Saverio976 commented on src/GraphicLibs/SDL/Sprite.cpp
> +    sprite = SDL_LoadBMP(path.data());
https://wiki.libsdl.org/SDL2/SDL_LoadBMP

non, ça prend que les formats bmp

2023-04-05 09:05 UTC, Saverio976 requested changes
load bmp load que des bmp

2023-04-05 09:06 UTC, KitetsuK commented on src/GraphicLibs/SDL/Sprite.cpp
> +    sprite = SDL_LoadBMP(path.data());
J utilise IMG_LoadTexture finalement

2023-04-05 14:08 UTC, Saverio976 commented on src/GraphicLibs/SDL/Sprite.cpp
> +    SDL_RenderPresent(this->_win);
cette ligne là est à mettre dans le DisplayModule::update

2023-04-05 14:13 UTC, Saverio976 approved these changes

2023-04-05 14:14 UTC, merged