Arcade 120 implementer map entity
X-R-G-B/Arcade pull request #91
Opened 2023-04-05 21:28 UTC by romainpanno

2023-04-05 21:30 UTC, romainpanno commented on src/GameLibs/Nibbler/Scene/GameScene.cpp
> +    return distr(gen);
wallah c'est mieux de std::rand, j'ai vu ca en tt cas et ca marche bien mais dites si il y a mieux

2023-04-05 21:30 UTC, romainpanno commented on src/GameLibs/Nibbler/Scene/GameScene.cpp
> +    std::string wallId;
wallid

2023-04-05 21:52 UTC, Saverio976 commented on src/GameLibs/Nibbler/Scene/GameScene.cpp
> +    return distr(gen);
fais ce que tu veux

2023-04-05 21:53 UTC, KitetsuK commented on src/GameLibs/Nibbler/Scene/GameScene.cpp
> +    std::string wallId;
WAAAAAAAAAALLIIIIID

2023-04-05 21:53 UTC, Saverio976 commented on src/GameLibs/Nibbler/Scene/GameScene.cpp
> +    std::string wallId;
smart

2023-04-05 21:55 UTC, Saverio976 requested changes

2023-04-05 21:55 UTC, Saverio976 commented on src/Arcade/ECS/ChangeLibComp.hpp
>  ** EPITECH PROJECT, 2023
c'est quoi ce fichier gros ?

il existe pas sur l'archi commune

2023-04-06 10:21 UTC, romainpanno commented on src/Arcade/ECS/ChangeLibComp.hpp
>  ** EPITECH PROJECT, 2023
je sais pas d'ou il sort moi :sob:

2023-04-06 11:11 UTC, guillaumeAbel approved these changes

2023-04-06 11:11 UTC, merged